services:
  postgres:
    image: postgres:15-alpine
    container_name: filestorage-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-filestorage}
      POSTGRES_USER: ${DB_USER:-filestorage_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-filestorage_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - filestorage-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-filestorage_user} -d ${DB_NAME:-filestorage}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: filestorage-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@filestorage.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-8081}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - filestorage-network

volumes:
  postgres_data:
    driver: local

  pgadmin_data:
    driver: local

networks:
  filestorage-network:
    driver: bridge