cors:
  allowed-origins:
    - http://localhost:5173
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

spring:
  application:
    name: FileStorage

  # Database Configuration - PostgreSQL
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:filestorage}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:filestorage_user}
    password: ${DB_PASSWORD:filestorage_password}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    # Flyway Configuration
    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
      sql-migration-prefix: V
      sql-migration-separator: __
      sql-migration-suffixes: .sql
      validate-on-migrate: true
      clean-disabled: true  # Safety: prevents accidental data deletion

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Server Configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:change_this_with_your_secret}
  expiration: 86_400_000 # 1 day in milliseconds

file:
  storage:
    max-file-size: 30_000_000 # 30 MB
    max-storage-per-user: 500_000_000 # 500 MB

# App Configuration
app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@example.com}
    password: ${ADMIN_PASSWORD:}
  storage:
    location: ./uploads

# Logging Configuration
logging:
  level:
    com.mvasilakos.filestorage: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/filestorage.log
    max-size: 10MB
    max-history: 10