spring:
  application:
    name: FileStorage

  # Database Configuration
  datasource:
    url: jdbc:h2:file:./data/filestore
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# Server Configuration
server:
  port: 8080

# Custom Storage Configuration
storage:
  location: ./uploads

file:
  storage:
    max-file-size: 30_000_000
    max-storage-per-user: 500_000_000

# Admin Configuration
app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    email: ${ADMIN_EMAIL:admin@example.com}
    password: ${ADMIN_PASSWORD:}

# Logging Configuration
logging:
  level:
    com.mvasilakos.filestorage: DEBUG
#    org.springframework.web: DEBUG
    root: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/filestorage.log
    max-size: 10MB
    max-history: 10